In [24]:
import pandas as pd
import numpy as np

In [4]:
# SE ACCEDIO A LA BASE IMPORTANDO PAQUETES PANDAS Y NUMPY
# LUEGO PD.READ.CSV IMPRIMIR LA BASE FELICIDAD
base_felicidad=pd.read_csv('https://raw.githubusercontent.com/cienciadedatos/datos-de-miercoles/master/datos/2019/2019-08-07/felicidad.csv')

In [5]:
base_felicidad

,pais,anio,escalera_vida,log_pib,soporte_social,expectativa_vida,libertad,generosidad,percepcion_corrupcion,afecto_positivo,afecto_negativo,confianza,calidad_democracia,calidad_entrega,de_escalera_pais_anio,gini_banco_mundial,gini_banco_mundial_promedio
0,Afghanistán,2008,3.723590,7.168690,0.450662,50.799999,0.718114,0.177889,0.881686,0.517637,0.258195,0.612072,-1.929690,-1.655084,1.774662,NaN,NaN
1,Afghanistán,2009,4.401778,7.333790,0.552308,51.200001,0.678896,0.200178,0.850035,0.583926,0.237092,0.611545,-2.044093,-1.635025,1.722688,NaN,NaN
2,Afghanistán,2010,4.758381,7.386629,0.539075,51.599998,0.600127,0.134353,0.706766,0.618265,0.275324,0.299357,-1.991810,-1.617176,1.878622,NaN,NaN
3,Afghanistán,2011,3.831719,7.415019,0.521104,51.919998,0.495901,0.172137,0.731109,0.611387,0.267175,0.307386,-1.919018,-1.616221,1.785360,NaN,NaN
4,Afghanistán,2012,3.782938,7.517126,0.520637,52.240002,0.530935,0.244273,0.775620,0.710385,0.267919,0.435440,-1.842996,-1.404078,1.798283,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1699,Zimbabue,2014,4.184451,7.562753,0.765839,52.380001,0.642034,-0.048634,0.820217,0.725214,0.239111,0.566209,-0.985267,-1.484067,2.079248,NaN,0.432
1700,Zimbabue,2015,3.703191,7.556052,0.735800,53.799999,0.667193,-0.097354,0.810457,0.715079,0.178861,0.590012,-0.893078,-1.357514,2.198865,NaN,0.432
1701,Zimbabue,2016,3.735400,7.538829,0.768425,54.400002,0.732971,-0.068105,0.723612,0.737636,0.208555,0.699344,-0.900649,-1.374650,2.776363,NaN,0.432
1702,Zimbabue,2017,3.638300,7.549491,0.754147,55.000000,0.752826,-0.069670,0.751208,0.806428,0.224051,0.682647,-0.988153,-1.350867,2.656848,NaN,0.432
1703,Zimbabue,2018,3.616480,7.553395,0.775388,55.599998,0.762675,-0.038384,0.844209,0.710119,0.211726,0.550508,NaN,NaN,2.498696,NaN,0.432

In [6]:
# SE UTILIZO LA INDEXACION BOOLEANA UTILIZANDO FILTRO DEL MAX Y MIN
data_bool=(base_felicidad.anio==max(base_felicidad.anio)) | (base_felicidad.anio==min(base_felicidad.anio))

In [7]:
data_observacion=base_felicidad[data_bool]
data_observacion[data_observacion['pais']=='Francia']

,pais,anio,escalera_vida,log_pib,soporte_social,expectativa_vida,libertad,generosidad,percepcion_corrupcion,afecto_positivo,afecto_negativo,confianza,calidad_democracia,calidad_entrega,de_escalera_pais_anio,gini_banco_mundial,gini_banco_mundial_promedio
496,Francia,2005,7.093393,10.505228,0.940338,71.300003,0.894819,NaN,0.687851,0.768988,0.225094,0.324884,0.939179,1.42579,1.614325,0.298,0.320923
508,Francia,2018,6.665904,10.573352,0.921463,73.800003,0.816377,-0.141567,0.581775,0.767313,0.282451,0.380547,NaN,NaN,1.599049,NaN,0.320923

In [8]:
# MEDIDA DE TENDENCCIA CENTRAL PARA EL PRIMER ANO A NIVEL MUNDIAL
promedio_gen_primer_ano=data_observacion[data_observacion['anio']==min(data_observacion['anio'])].escalera_vida.mean()
promedio_gen_primer_ano

6.446164272449635

In [9]:
# MEDIDA DE TENDENCIA CENTRAL PARA EL ULTIMO ANO NIVEL MUNDIAL
promedio_gen_ultimo_ano=data_observacion[data_observacion['anio']==max(data_observacion['anio'])].escalera_vida.mean()
promedio_gen_ultimo_ano

5.502134340650895

In [10]:
# DESVIACION ESTANDAR PARA EL PRIMER ANO A NIVEL GLOBAL
promedio_disp_primer_ano=data_observacion[data_observacion['anio']==min(data_observacion['anio'])].escalera_vida.std()
promedio_disp_primer_ano

0.9191426322726484

In [11]:
# DESVIACION ESTANDAR ULTIMO ANO A NIVEL GLOBAL
promedio_disp_ultimo_ano=data_observacion[data_observacion['anio']==max(data_observacion['anio'])].escalera_vida.std()
promedio_disp_ultimo_ano

1.1034612436939357

In [12]:
# CON LA INDEXACION BOOLEANA TAMBIEN SE FILTRO PARA LOS PAISES CANADA Y FRANCIA
data_paises = data_observacion[data_observacion['pais'].isin(['Canadá','Francia'])]

In [13]:
data_paises

,pais,anio,escalera_vida,log_pib,soporte_social,expectativa_vida,libertad,generosidad,percepcion_corrupcion,afecto_positivo,afecto_negativo,confianza,calidad_democracia,calidad_entrega,de_escalera_pais_anio,gini_banco_mundial,gini_banco_mundial_promedio
258,Canadá,2005,7.418048,10.608347,0.961552,71.300003,0.957306,0.244575,0.502681,0.838544,0.233278,0.442818,1.168249,1.748819,1.636804,NaN,0.336800
270,Canadá,2018,7.175497,10.701248,0.922719,73.599998,0.945783,0.097966,0.371741,0.823669,0.259398,0.610467,NaN,NaN,1.764457,NaN,0.336800
496,Francia,2005,7.093393,10.505228,0.940338,71.300003,0.894819,NaN,0.687851,0.768988,0.225094,0.324884,0.939179,1.425790,1.614325,0.298,0.320923
508,Francia,2018,6.665904,10.573352,0.921463,73.800003,0.816377,-0.141567,0.581775,0.767313,0.282451,0.380547,NaN,NaN,1.599049,NaN,0.320923

In [22]:
# Crear un DataFrame General
df = pd.DataFrame({
     'paises':['Canadá','Canadá','Francia','Francia','Mundial','Mundial'],
     'anio':['2005','2018','2005','2018','2005','2018'],
     'escalera_vida':  [7.418048, 7.175497, 7.093393, 6.665904,promedio_gen_primer_ano,promedio_gen_ultimo_ano]})
df

    paises  anio  escalera_vida
0   Canadá  2005       7.418048
1   Canadá  2018       7.175497
2  Francia  2005       7.093393
3  Francia  2018       6.665904
4  Mundial  2005       6.446164
5  Mundial  2018       5.502134

In [23]:
# Crear Data Frame Canada
df_Canadá = pd.DataFrame({
     'pais':['Canadá','Canadá','Mundial','Mundial'],
     'anio':['2005','2018','2005','2018'],
     'escalera_vida':  [7.418048, 7.175497,promedio_gen_primer_ano,promedio_gen_ultimo_ano]})
df_Canadá

      pais  anio  escalera_vida
0   Canadá  2005       7.418048
1   Canadá  2018       7.175497
2  Mundial  2005       6.446164
3  Mundial  2018       5.502134

In [16]:
# Crear un DataFrame Francia
df_francia = pd.DataFrame({
     'pais':['Francia','Francia','Mundial','Mundial'],
     'anio':['2005','2018','2005','2018'],
     'escalera_vida':  [7.093393, 6.665904,promedio_gen_primer_ano,promedio_gen_ultimo_ano]})
df_francia

      pais  anio  escalera_vida
0  Francia  2005       7.093393
1  Francia  2018       6.665904
2  Mundial  2005       6.446164
3  Mundial  2018       5.502134

In [19]:
#-----------ARGUMENTO TAREA FELICIDAD MEDIDA DE TENDENCIA CENTRAL-----------------
#Canadá tiene mejor nivel de felicidad en ambos años. En 2005: 7.42, en comparacion al promedio global de 2005 que es 6.45,
#En 2018: 7.17, en comparacion al promedio global de 2018 que es 5.50
#su población tiene alta calidad de vida, mejores condiciones a nivel social, económico, laboral.

#Comparar el promedio de Francia con el promedio global, después de Canadá también se distingue por ser un
#Francia tambien tiene mejor nivel de felicidad en ambos años. En 2005: 7.09, en comparacion al promedio global de 2005 que es 6.45,
#En 2018: 6.66, en comparacion al promedio global de 2018 que es 5.50.
# Francia es país feliz tiene buenas condiciones de vida un fuerte mercado laboral,
# buen sistema educativo.

# Ambos paises pueden ser considerados aceptables ya que cuentan con un mayor nivel de felicidad en relacion al promedio mundial de esos años.


#Canadá también en comparación con Francia cuento con mejores condiciones, 
# la diferencia no es considerable pero cuenta con un mayor nivel de felicidad
#Canada En 2005: 7.42, en comparacion a Francia en 2005 que es 7.09,
#Canada En 2018: 7.17, en comparacion a Francia en 2018 que es 6.66.
# Canadá se distingue por su alto Índice de Desarrollo Humano 
# por ser uno de los países del mundo donde su población es mas feliz, 
# además poseen un alto respeto por las reglas de convivencia y urbanidad, 
# lo que hace de Canadá un país ordenado, tranquilo y seguro para vivir.

In [20]:
df_general = pd.DataFrame({
     'Poblacion':['Mundial','Mundial'],
     'anio':['2005','2018'],
     'Prom_escalera_vida':  [promedio_gen_primer_ano,promedio_gen_ultimo_ano],
     'Desv_escalera_vida':  [promedio_disp_primer_ano,promedio_disp_ultimo_ano]})
df_general

  Poblacion  anio  Prom_escalera_vida  Desv_escalera_vida
0   Mundial  2005            6.446164            0.919143
1   Mundial  2018            5.502134            1.103461

In [21]:
#--------ARGUMENTO DESVIACION ESTANDAR std------------
# entre más dispersa esta la distribución de datos más grande es su desviación estándar, 
# centrándose en la distancia de los diferentes valores respecto al valor medio.
#Podemos concluir que en el 2005 los niveles de felicidad de los paises no estaban tan alejados de su media,
#mientras que en el 2018 contamos con valores muy grandes o pequeños que ocasionan una mayor dispersion